In [1]:
import numpy as np

list1= [1,2,3,4]
a = np.array(list1)
print(a.shape)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(4,)
(2, 3)


In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

#addition
c = a+b
print(c)

#subtraction
c=a-b
print(c)

#Multiplication
c = a*b
print(c)

#Division
c = a/b
print(c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
